### ISSUE TITLE
Failure to create report with NullPointerException on a minimal project

### ISSUE THREAD

**Issue by nespera** [albuch/sbt-dependency-check#253] opened 2022-05-25 10:40 UTC
#### Describe the bug
Running dependency check on a minimal project fails with a NullPointerException

#### Version of sbt-dependency-check used
The problem occurs using version 4.1.0 of the the plugin.

#### Log file
```
[error] Failed creating report:
[error]   Failed to request component-reports
[error]   - null
[error] One or more exceptions occurred during analysis:
[error] org.owasp.dependencycheck.exception.ExceptionCollection: One or more exceptions occurred during analysis:
[error] 	AnalysisException: Failed to request component-reports
[error] 		caused by NullPointerException: null
[error] 	at org.owasp.dependencycheck.Engine.analyzeDependencies(Engine.java:665)
[error] 	at net.vonbuchholtz.sbt.dependencycheck.DependencyCheckPlugin$.createReport(DependencyCheckPlugin.scala:597)
[error] 	at net.vonbuchholtz.sbt.dependencycheck.DependencyCheckPlugin$.$anonfun$checkTask$6(DependencyCheckPlugin.scala:351)
[error] 	at net.vonbuchholtz.sbt.dependencycheck.DependencyCheckPlugin$.withEngine(DependencyCheckPlugin.scala:617)
[error] 	at net.vonbuchholtz.sbt.dependencycheck.DependencyCheckPlugin$.$anonfun$checkTask$2(DependencyCheckPlugin.scala:349)
[error] 	at net.vonbuchholtz.sbt.dependencycheck.DependencyCheckPlugin$.$anonfun$checkTask$2$adapted(DependencyCheckPlugin.scala:312)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error] 	at sbt.Execute.work(Execute.scala:291)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error] 	at java.base/java.lang.Thread.run(Thread.java:834)
```

#### To Reproduce
Created a minimal project using build.sbt:
```
Global / dependencyCheckFormats := Seq("HTML", "JSON")

lazy val root = (project in file("."))
  .settings(
	dependencyCheckSkipTestScope := false
  )
```
and project/plugins.sbt:
```
addSbtPlugin("net.vonbuchholtz" % "sbt-dependency-check" % "4.1.0")
```
then ran `dependencyCheck`

#### Expected behavior
A report should be generated

#### Additional context
Originally I was running plugin 3.1.3, which gave a similar error.

**Comment by nespera** [comment] 2022-05-25 10:46
I notice that if I poke at the `/api/v3/component-report` endpoint here https://ossindex.sonatype.org/rest it gives me a 500 error

**Comment by Wouter-M** [comment] 2022-05-25 12:46
There's has been a change to some API used for the checks. A lot of people are having similar issues, see also https://github.com/jeremylong/DependencyCheck/issues/4535#issuecomment-1137136998.

**Comment by nespera** [comment] 2022-05-25 12:56
It seems that adding `dependencyCheckOSSIndexAnalyzerEnabled := Some(false)` to build.sbt is a partial workaround, although it is turning off part of the functionality

**Comment by albuch** [comment] 2022-05-26 07:43
This issue (and several others along the line with rate limiting) is caused by a recent change from OSSIndex. As far as I can see from the upstream most issues are fixed now by OSSIndex, however if you still face NPE errors you should mention these at https://github.com/jeremylong/DependencyCheck/issues/4535 as the OSSIndex developer is active in the issue.

If you face rate limiting erors you can consider creating an OSSIndex user account and set `dependencyCheckOSSIndexAnalyzerUsername` and `dependencyCheckOSSIndexAnalyzerPassword` in your build.sbt to reduce the risk of rate limitng. Alternatively you can deactivated the analyzer with `dependencyCheckOSSIndexAnalyzerEnabled := Some(false)`.

I'm going to close this issue as there is nothing we can do here for the sbt plugin. This has to be fiexed by either DependencyCheck and/or OSSIndex.

**Closed by albuch** 2022-05-26 07:43 UTC
Labels: bug
