### ISSUE TITLE
Running test with dependencyCheck

### ISSUE THREAD

**Issue by sfosdal** [albuch/sbt-dependency-check#101] opened 2019-11-08 00:59 UTC
I don't think I'm doing anything odd, but:

When I run
```
sbt dependencyCheck
```
I get the dependency report I expect.

When I run
```
sbt clean test
```
All my tests pass, as expected.

but

when I run
```
sbt clean test dependencyCheck
```
the tests pass, but then I get a lot of errors:
```
2019-11-07 16:55:33,877 level=ERROR [REDACTED-akka.actor.default-dispatcher-3]c.c.n.s.s.REDACTED requestId=[] callerId=[] - REDACTED
java.lang.RuntimeException: Can't log call to mock object, have expectations been verified already?
	at org.scalamock.function.FakeFunction.handle(FakeFunction.scala:47)
	at org.scalamock.function.FakeFunction0.apply(FakeFunction.scala:57)
```

**Comment by sfosdal** [comment] 2019-11-08 00:59
Is this a bug, or me not understanding how to use `dependencyCheck`?

**Comment by sfosdal** [comment] 2019-11-08 01:08
Additionally, running:
```
sbt clean dependencyCheck test
```
works fine.

**Comment by albuch** [comment] 2019-11-18 10:41
Thanks for the report. I'll have a look at it.

**Comment by albuch** [comment] 2020-01-12 19:19
@sfosdal could you provide a minimal test project? I could not reproduce with a vanilla project.

**Comment by albuch** [comment] 2020-10-16 15:25
I~ll go ahead and close the issue. Feel free to re/open.

**Closed by albuch** 2020-10-16 15:25 UTC
Labels: question
